### ISSUE TITLE
Is it possible to configure patches without the normal unity GUI?

### ISSUE THREAD

**Issue by Cuphead74832** [nomnomab/lc-project-patcher#10]
Hey i just got a VPS to compile stuff but its cheap so i only have a CLI so if you could tell me how to manually deploy the patcher config file and what to put in that file with the patches "skip intro and main menu" applied that would be cool. Also today i will be down and maybe tomorrow my new drive has arrived and i have to clone my data to it.

**Comment by nomnomab** [comment]
I have no idea what you are asking me. The tool relies on using an editor window to set up information. There is no CLI usage for it.

**Comment by Cuphead74832** [comment]
I mean if there is a way so i can create that file into the project manually via text editors and what do i put in it.

**Comment by nomnomab** [comment]
I can give the yaml of the asset but it won't function properly without being an actual asset (needs a meta file to even be one), and you still have to assign editor-specific preferences to even run the patcher. The script guid will be wrong as well.

So if this helps in some way, cool, otherwise this tool is not meant for cli usage. 👍

```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!114 &11400000
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: e72c84e7afaa4515877e484af6361412, type: 3}
  m_Name: LCPatcherRuntimeSettings
  m_EditorClassIdentifier: 
  SkipIntro: 1
  SkipMainMenu: 1
  SaveFileIndex: 0
  SaveFileResetBeforeLoad: 0
  BepInExLocation: 0
  CustomBepInExLocation: 
  LoadProjectPlugins: 1
  InfiniteHealth: 0
  InfiniteStamina: 0
  SkipTerminalIntro: 0
  StartingCredits: -1
  Time: 0
  AutoLoadMoon: 0
  AutoLoadMoonReference: {fileID: 0}
  AutoLoadMoonSceneName: 
  LoadPosterizationShader: 0
  DisableAutomaticScriptableObjectReloading: 0
  DisablePreInitScriptCoroutineReplacer: 0
```
